import React, { useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { ArrowLeft, Smartphone, KeyRound, ShieldCheck, Leaf, Fingerprint, Gauge } from 'lucide-react';
import { AuthBackground } from '@/components/ui/AuthBackground';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { BrixLogo } from '@/components/common/BrixLogo';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';

const FAQ = [
  {
    value: 'brix',
    icon: Leaf,
    question: 'What is BRIXit?',
    answer: (
      <p>
        BRIXit is a community app for measuring the nutritional quality of fresh produce.
        Using a handheld refractometer, you scan a fruit or vegetable to get its BRIXit
        score: a simple number reflecting how it was grown. Two carrots can look identical
        yet score very differently. BRIXit lets you measure, compare, and share results
        with people around the world.
      </p>
    ),
  },
  {
    value: 'measure',
    icon: Gauge,
    question: 'How do I measure produce?',
    answer: (
      <p>
        You'll need a handheld refractometer, an inexpensive optical tool. Squeeze a drop
        of juice from the produce onto the lens and read the number: that's your BRIXit
        score. Record it in the app with the crop and where you bought it, and it joins
        the shared map for everyone to compare.
      </p>
    ),
  },
  {
    value: 'wallet',
    icon: KeyRound,
    question: 'Why do we use a wallet instead of a password?',
    answer: (
      <p>
        Passwords get stored on company servers, which get breached, leaked, or sold.
        BRIXit avoids that entirely. Instead, your identity lives in a wallet on your own
        device, holding a private key only you control. When you sign in, your wallet
        proves who you are through a cryptographic handshake. There's no password on our
        servers for anyone to steal.
      </p>
    ),
  },
  {
    value: 'identity-key',
    icon: Fingerprint,
    question: 'What is an identity key and why do we need one?',
    answer: (
      <p>
        Your identity key is a public code generated by your wallet, like a permanent
        username. It lets BRIXit link your submissions to one consistent identity, keeping
        data trustworthy, without knowing who you are. The key is public, but only you can
        prove you own it, since the matching private key never leaves your device. Your
        wallet handles it automatically.
      </p>
    ),
  },
  {
    value: 'certificate',
    icon: ShieldCheck,
    question: 'What is a certificate and why does BRIX use one?',
    answer: (
      <p>
        A certificate proves you're a genuine member, not a bot. When you create an
        account, BRIXit issues a membership certificate into your wallet, signed by us, so
        the app can verify it without any server lookup. It holds only what you choose to
        share: an optional display name and email. You keep it in your wallet and can
        remove it anytime.
      </p>
    ),
  },
  {
    value: 'mycelia',
    icon: Smartphone,
    question: 'What is the Mycelia app?',
    answer: (
      <p>
        Mycelia is the wallet app BRIXit is built on. It manages your identity key and
        certificates for you, so you never handle cryptography yourself. Create your
        identity in Mycelia once, then open BRIXit from inside it to sign in automatically.
        On desktop, scan a QR code with Mycelia to connect. The same identity works across
        other compatible apps too.
      </p>
    ),
  },
];

export default function Help() {
  const navigate = useNavigate();
  const location = useLocation();

  const hashSection = location.hash.replace('#', '');
  const validHash = FAQ.some(f => f.value === hashSection) ? hashSection : null;
  const defaultOpen = validHash ? [validHash] : ['brix'];

  useEffect(() => {
    if (!validHash) return;
    const el = document.getElementById(validHash);
    if (el) setTimeout(() => el.scrollIntoView({ behavior: 'smooth', block: 'start' }), 150);
  }, [validHash]);

  return (
    <AuthBackground>
      <div className="w-full max-w-xl mx-auto space-y-6 pt-8 self-start">

        {/* Back */}
        <Button
          variant="ghost"
          onClick={() => navigate(-1)}
          className="flex items-center gap-2 -ml-2"
        >
          <ArrowLeft className="w-4 h-4" />
          Back
        </Button>

        {/* Header */}
        <div className="text-center">
          <BrixLogo height="5rem" color="white" className="mx-auto mb-4" />
          <h1 className="text-2xl font-display font-bold text-on-bg-text">How BRIXit works</h1>
          <p className="text-on-bg-body text-sm mt-1">Everything you need to know to get started</p>
        </div>

        {/* FAQ accordion */}
        <Accordion type="multiple" defaultValue={defaultOpen} className="space-y-2">
          {FAQ.map(({ value, icon: Icon, question, answer }) => (
            <AccordionItem
              key={value}
              value={value}
              id={value}
              className="border border-hairline rounded-xl bg-card overflow-hidden px-4"
            >
              <AccordionTrigger className="hover:no-underline py-4 gap-3 text-left">
                <span className="flex items-center gap-3">
                  <Icon className="w-4 h-4 text-green-fresh shrink-0" />
                  <span className="font-semibold text-sm text-text-dark">{question}</span>
                </span>
              </AccordionTrigger>
              <AccordionContent className="text-sm text-text-mid leading-relaxed pb-4">
                {answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>

        {/* Getting started */}
        <Card className="border-hairline bg-surface-canvas">
          <CardHeader className="pb-2">
            <CardTitle className="text-base text-green-mid">Getting started</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            <ol className="text-sm text-text-dark space-y-2 list-none">
              {[
                'Download the Mycelia app on your phone.',
                'Create your identity inside Mycelia. It only takes a minute.',
                'Open BRIXit from within the Mycelia app and you will be signed in automatically.',
              ].map((step, i) => (
                <li key={i} className="flex items-start gap-3">
                  <span className="w-5 h-5 rounded-full bg-green-fresh text-white text-xs flex items-center justify-center shrink-0 mt-0.5">
                    {i + 1}
                  </span>
                  {step}
                </li>
              ))}
            </ol>
            <div className="pt-2">
              <a
                href="https://mycelia.life"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 text-sm font-medium text-green-fresh hover:text-green-mid underline underline-offset-2"
              >
                <Smartphone className="w-4 h-4" />
                Download Mycelia
              </a>
            </div>
          </CardContent>
        </Card>

        {/* On desktop */}
        <p className="text-center text-xs text-on-bg-muted pb-4">
          On a desktop? Choose <em>connect via mobile QR</em> on the login screen and scan the code with your Mycelia app.
        </p>

      </div>
    </AuthBackground>
  );
}
